FROM amazoncorretto:17-alpine3.17-jdk
LABEL auther="dhille"
LABEL project="learing"
EXPOSE 8080
# create user
RUN addgroup -g 1006 dhilli && adduser -h "/dhilli" -u 1006 -G dhilli -s /bin/bash -D dhilli
# switch the user
USER dhilli
ADD --chown=spc:spc https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-3.1.0-SNAPSHOT.jar \
 /spc/spring-petclinic-3.1.0-SNAPSHOT.jar
WORKDIR /spc
CMD [ "java", "jar", "spring-petclinic-3.1.0-SNAPSHOT.jar"]